version: '3.7'

services:
  # --- Database ---
  mysql-db:
    image: mysql:5.7
    container_name: school-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  # --- Backend ---
  backend:
    image: fgmuneeb/school-backend:latest  # Docker Hub se ayega
    container_name: school-backend
    restart: always
    ports:
      - "3500:3500"
    environment:
      host: mysql-db
      user: user
      password: password
      database: school
    depends_on:
      - mysql-db

  # --- Frontend ---
  frontend:
    image: fgmuneeb/school-frontend:latest # Docker Hub se ayega
    container_name: school-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
