server {
    listen 80;

    # 1. Frontend: React ki files dikhao
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # Ye Refresh wala 404 theek karega
    }

    # 2. Backend: API calls ko Chef (Backend) k pas bhejo
    # Logic: Jab browser '/addstudent' mangay, to 'school-backend:3500' par forward kardo
    location /addstudent {
        proxy_pass http://school-backend:3500;
    }

    location /addteacher {
        proxy_pass http://school-backend:3500;
    }

    location /student {
        proxy_pass http://school-backend:3500;
    }

    location /teacher {
        proxy_pass http://school-backend:3500;
    }

    # 3. Error Handling
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
